<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <parent>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-parent</artifactId>
    <version>4.1.1</version>
    <relativePath/>
  </parent>

  <groupId>com.jordimarcal.telemetry</groupId>
  <artifactId>kafka-adapter-telemetry</artifactId>
  <version>0.1.0-SNAPSHOT</version>
  <packaging>pom</packaging>
  <name>kafka-adapter-telemetry</name>
  <description>Adapter telemetry pipeline: Kafka + Oracle, Java 25, hexagonal</description>

  <modules>
    <module>contracts</module>
    <module>adapter-gateway</module>
    <module>telemetry-hub</module>
  </modules>

  <properties>
    <java.version>25</java.version>
  </properties>
</project>
