spring:
  application:
    name: telemetry-hub
  threads:
    virtual:
      enabled: true
  datasource:
    url: jdbc:oracle:thin:@//${ORACLE_HOST:localhost}:${ORACLE_PORT:1521}/${ORACLE_SERVICE:telemetry}
    username: ${ORACLE_USER:telemetry}
    password: ${ORACLE_PASS:telemetry}
  flyway:
    enabled: true
  web:
    resources:
      static-locations: classpath:/static, file:dashboard/dist/
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP:localhost:9092}
    consumer:
      group-id: telemetry-hub
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.trusted.packages: com.jordimarcal.telemetry.contracts
        spring.json.value.default.type: com.jordimarcal.telemetry.contracts.TelemetryEvent
        spring.json.use.type.headers: false
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

server:
  port: 8082

management:
  endpoints:
    web:
      exposure:
        include: health
